### ISSUE TITLE
Does not count lines of .cs files.

### ISSUE THREAD

**Issue by mxjp** [cb372/line-count#1]
I currently have a c# project and tried to count the lines of cody using the hosted version of line-count here: http://line-count.herokuapp.com/ with the repository https://github.com/q-zero/overpass-engine

But it only displays 'Text [..] 154 lines', and nothing else.

**Comment by cb372** [comment]
Would you like to submit a PR to fix it? You just need to add an entry to the `codeFileTypes` hash in https://github.com/cb372/line-count/blob/master/parser.js

I'm happy to merge a PR and redeploy to Heroku

**Comment by cb372** [comment]
Fixed by #2 

Thanks for the PR. I've deployed it to Heroku.

**Comment by mxjp** [comment]
It works, thanks!
